@startuml name hokotrok
left to right direction
skinparam packageStyle rectangle

actor "Takarító" as Cleaner
actor "Buszvezető" as BusDriver
actor "Rendszer" as System << Automatic >>

rectangle "Hókotró" {
    (Hókotró útvonalának megadása) as UC1
    (Kotrófej cseréje a hókotrón) as UC2
    (Felszerelés vásárlása) as UC3
    (Új hókotró vásárlása) as UC7
    (Sárkány fej használata) as UC9
    (Sószóró fej alkalmazása) as UC11
    (Buszvezető útvonalának megadása) as UC4
    (Baleset jégpáncélon) as UC5
    (Busz elakadása a magas hóban) as UC6
    (Útszakasz jegessé válása) as UC8
    (Kereszteződésben való áthaladás) as UC10
}

' Takarító kapcsolatok
Cleaner -- UC1 
Cleaner -- UC2 
Cleaner -- UC3 
Cleaner -- UC7 
Cleaner -- UC9 
Cleaner -- UC11 
Cleaner -- UC10 

' Buszvezető kapcsolatok
BusDriver -- UC4 
BusDriver -- UC5 
BusDriver -- UC6 
BusDriver -- UC10 

' Rendszer kapcsolatok (másodlagos aktor)
UC1 -- System 
UC2 -- System 
UC3 -- System 
UC4 -- System 
UC7 -- System 
UC8 -- System 
UC9 -- System 
UC10 -- System 
UC11 -- System
@enduml