@startuml name hokotrok
left to right direction
skinparam packageStyle rectangle
skinparam shadowing false
skinparam usecase {
    BackgroundColor White
    BorderColor Black
    RectangleDisplay true
}

actor "Takarító" as T
actor "Buszvezető" as B

rectangle "Hókotrók" {
  usecase UC1 as "Hókotró útvonalának megadása"
  usecase UC2 as "Kotrófej cseréje a hókotrón"
  usecase UC3 as "Felszerelés vásárlása"
  usecase UC4 as "Buszvezető útvonalának megadása"
  usecase UC5 as "Egy másik jármű belecsúszik a buszvezető által vezetett buszba"
  usecase UC6 as "A busz elakad a magas hóban"

  ' Sima vonalak az aktorok és a fő Use Case-ek között
  T -- UC1
  T -- UC3
  
  ' A kotrófejet a kezdetihez képest expliciten akkor cseréljük ha a munka közben váratlan eset adódik (Extend)
  UC1 <.. UC2 : <<extend>>

  B -- UC4
' Szintén váratlan esetek a busszal kapcsolatban ha elakad vagy becsúszik egy másik jármű (Extend)
  UC4 <.. UC5 : <<extend>>
  UC4 <.. UC6 : <<extend>>
}
@enduml